# Generated by Django 4.1.6 on 2023-02-06 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=50, verbose_name='sarlavha')),
                ('sana', models.DateField()),
                ('maqola', models.TextField(max_length=1000)),
                ('rasm', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Intert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('vedio', models.URLField()),
                ('sarlavha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blok_app.maqola')),
            ],
        ),
    ]
