# Generated by Django 4.1.6 on 2023-02-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blok_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='rasm',
            field=models.FileField(upload_to=''),
        ),
    ]
